mushrooms

## Load And Preview Dataset

In [2]:
import pandas as pd

pd.set_option('display.max_columns', None)

In [3]:
def load_and_preview_data(file_path='../Data/raw_data.csv', header=True):
    """
    Load and process mushroom data from CSV file.
    
    Parameters:
    file_path (str): Path to the CSV file
    header (bool): Whether the file has a header row
    
    Returns:
    pandas.DataFrame: Processed mushroom data
    """
    # Read CSV with semicolon separator (not comma)
    df = pd.read_csv(file_path, sep=';')
    
    # Display basic info about the dataset
    print(f"Dataset shape: {df.shape}")
    print(f"Columns: {list(df.columns)}")
    print(f"Missing values per column:")
    print(df.isnull().sum())
    
    return df

In [4]:
df = load_and_preview_data()
df

Dataset shape: (61069, 21)
Columns: ['class', 'cap-diameter', 'cap-shape', 'cap-surface', 'cap-color', 'does-bruise-or-bleed', 'gill-attachment', 'gill-spacing', 'gill-color', 'stem-height', 'stem-width', 'stem-root', 'stem-surface', 'stem-color', 'veil-type', 'veil-color', 'has-ring', 'ring-type', 'spore-print-color', 'habitat', 'season']
Missing values per column:
class                       0
cap-diameter                0
cap-shape                   0
cap-surface             14120
cap-color                   0
does-bruise-or-bleed        0
gill-attachment          9884
gill-spacing            25063
gill-color                  0
stem-height                 0
stem-width                  0
stem-root               51538
stem-surface            38124
stem-color                  0
veil-type               57892
veil-color              53656
has-ring                    0
ring-type                2471
spore-print-color       54715
habitat                     0
season                      0
dtype: int64

,class,cap-diameter,cap-shape,cap-surface,cap-color,does-bruise-or-bleed,gill-attachment,gill-spacing,gill-color,stem-height,stem-width,stem-root,stem-surface,stem-color,veil-type,veil-color,has-ring,ring-type,spore-print-color,habitat,season
0,p,15.26,x,g,o,f,e,NaN,w,16.95,17.09,s,y,w,u,w,t,g,NaN,d,w
1,p,16.60,x,g,o,f,e,NaN,w,17.99,18.19,s,y,w,u,w,t,g,NaN,d,u
2,p,14.07,x,g,o,f,e,NaN,w,17.80,17.74,s,y,w,u,w,t,g,NaN,d,w
3,p,14.17,f,h,e,f,e,NaN,w,15.77,15.98,s,y,w,u,w,t,p,NaN,d,w
4,p,14.64,x,h,o,f,e,NaN,w,16.53,17.20,s,y,w,u,w,t,p,NaN,d,w
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61064,p,1.18,s,s,y,f,f,f,f,3.93,6.22,NaN,NaN,y,NaN,NaN,f,f,NaN,d,a
61065,p,1.27,f,s,y,f,f,f,f,3.18,5.43,NaN,NaN,y,NaN,NaN,f,f,NaN,d,a
61066,p,1.27,s,s,y,f,f,f,f,3.86,6.37,NaN,NaN,y,NaN,NaN,f,f,NaN,d,u
61067,p,1.24,f,s,y,f,f,f,f,3.56,5.44,NaN,NaN,y,NaN,NaN,f,f,NaN,d,u
61068,p,1.17,s,s,y,f,f,f,f,3.25,5.45,NaN,NaN,y,NaN,NaN,f,f,NaN,d,u

In [5]:
def display_class_distribution(df):
    """
    Display the class distribution of the mushroom dataset.
    
    Parameters:
    df (pandas.DataFrame): The mushroom dataset
    
    Returns:
    None: Prints the distribution and percentages
    """
    print("Class Distribution:")
    print("=" * 30)
    
    # Count values in the 'class' column
    class_counts = df['class'].value_counts()
    print(f"Total samples: {len(df)}")
    print()
    
    for class_label, count in class_counts.items():
        percentage = (count / len(df)) * 100
        class_name = "Poisonous" if class_label == 'p' else "Edible"
        print(f"{class_name} ({class_label}): {count:,} samples ({percentage:.2f}%)")
    
    print()

    print("Class Balance:")
    ratio = class_counts.max() / class_counts.min()
    print(f"Imbalance ratio: {ratio:.2f}:1")
    
    return class_counts

In [6]:
# Display class distribution
class_dist = display_class_distribution(df)

Class Distribution:
==============================
Total samples: 61069

Poisonous (p): 33,888 samples (55.49%)
Edible (e): 27,181 samples (44.51%)

Class Balance:
Imbalance ratio: 1.25:1

## Clean Data

Drop Columns With over 50% missing data

In [7]:
columns_to_drop = ['stem-root','veil-type', 'veil-color',  'stem-surface', 'spore-print-color']
df = df.drop(columns=columns_to_drop)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61069 entries, 0 to 61068
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   class                 61069 non-null  object
 1   cap-diameter          61069 non-null  float64
 2   cap-shape             61069 non-null  object
 3   cap-surface           46949 non-null  object
 4   cap-color             61069 non-null  object
 5   does-bruise-or-bleed  61069 non-null  object
 6   gill-attachment       51185 non-null  object
 7   gill-spacing          36006 non-null  object
 8   gill-color            61069 non-null  object
 9   stem-height           61069 non-null  float64
 10  stem-width            61069 non-null  float64
 11  stem-color            61069 non-null  object
 12  has-ring              61069 non-null  object
 13  ring-type             58598 non-null  object
 14  habitat               61069 non-null  object
 15  season                61069 non-null  object
dtypes: float64(3), object(13)
memory usage: 7.5+ MB

In [8]:
df.isnull().sum()

class                       0
cap-diameter                0
cap-shape                   0
cap-surface             14120
cap-color                   0
does-bruise-or-bleed        0
gill-attachment          9884
gill-spacing            25063
gill-color                  0
stem-height                 0
stem-width                  0
stem-color                  0
has-ring                    0
ring-type                2471
habitat                     0
season                      0
dtype: int64

In [9]:
# get summary stats for numeric columns
df.describe()

       cap-diameter   stem-height    stem-width
count  61069.000000  61069.000000  61069.000000
mean       6.733854      6.581538     12.149410
std        5.264845      3.370017     10.035955
min        0.380000      0.000000      0.000000
25%        3.480000      4.640000      5.210000
50%        5.860000      5.950000     10.190000
75%        8.540000      7.740000     16.570000
max       62.340000     33.920000    103.910000

In [72]:
# split data into train and test before imputation or encoding
from sklearn.model_selection import train_test_split
train_df, test_df = train_test_split(df, test_size = .2, random_state=42)

## original preprocessing

**Impute train and test data**
* We will use KNN imputation on the columns with less than 50% missing data.
* We use k = 5.

In [17]:
# standardize numeric columns
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
numeric_cols = ['cap-diameter', 'stem-height', 'stem-width']

# standardize train data
std_train_df = train_df.copy()
std_train_df[numeric_cols] = scaler.fit_transform(train_df[numeric_cols])
std_train_df.describe()

# standardize test data
std_test_df = test_df.copy()
std_test_df[numeric_cols] = scaler.transform(test_df[numeric_cols])
std_test_df.describe()

In [22]:
std_train_df.loc[std_train_df['cap-surface'].notna()]

,class,cap-diameter,cap-shape,cap-surface,cap-color,does-bruise-or-bleed,gill-attachment,gill-spacing,gill-color,stem-height,stem-width,stem-color,has-ring,ring-type,habitat,season
42308,e,-0.813292,x,y,w,f,e,c,p,-0.906761,-0.138059,w,t,e,g,u
39798,p,-0.397978,c,i,y,f,NaN,c,r,-0.043783,-0.486727,w,f,f,d,u
40487,p,0.185757,x,t,n,f,s,NaN,n,-0.141984,-0.379445,n,f,f,d,w
27727,p,0.036474,x,d,n,t,d,c,w,0.250820,-0.243355,e,f,f,d,a
25153,e,1.852752,x,t,k,f,a,d,y,0.063345,1.020196,w,f,f,d,a
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44732,p,0.245088,b,y,w,f,NaN,NaN,p,1.908333,0.409281,w,f,f,d,a
54343,p,-0.229556,s,d,y,f,d,c,y,-1.222195,-0.618844,o,f,f,h,u
38158,p,0.183843,x,e,n,f,a,NaN,n,1.598851,0.313919,n,f,f,h,a
15795,p,0.011593,x,s,n,t,s,d,r,-0.043783,0.412261,w,f,f,d,u
56422,p,0.076665,o,t,r,f,NaN,c,y,-1.478112,0.276171,n,f,f,d,a

In [23]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import Pipeline

def knn_impute_categorical(df, target):
    """
    Impute missing categorical values using KNN classifier.

    Target: column to impute
    df: dataframe with missing values
    """

    mask = df[target].notna()  # rows where column does not have missing values

    # build train_columns based on columns without nulls 
    _X_train_tmp = df.loc[mask].drop(columns=[target])
    train_columns = _X_train_tmp.columns[_X_train_tmp.isnull().sum() == 0].tolist() # train on columns without nulls

    # training data where column is not null
    X_train = df.loc[mask, train_columns]
    y_train = df.loc[mask, target]

    # predict(impute) on rows where column ARE NULL
    X_missing = df.loc[~mask, train_columns]

    # define numeric and categorical columns
    num_cols = ['cap-diameter','stem-height','stem-width']
    cat_cols = [c for c in train_columns if c not in num_cols + [target]]

    # create preprocessor
    pre = ColumnTransformer([
        ("num", StandardScaler(), num_cols),
        ("cat", OneHotEncoder(handle_unknown="ignore"), cat_cols),
    ])

    # knn classifier pipeline
    clf = Pipeline([
        ("pre", pre),
        ("knn", KNeighborsClassifier(n_neighbors=5, weights="distance"))
    ])

    # fit knn classifier and predict (IMPUTE) missing values
    clf.fit(X_train, y_train)
    df.loc[~mask, target] = clf.predict(X_missing)  # fill in missing cap-surface values

    return df

In [42]:


# categorical columns with missing values
categorical_cols_with_nans = ['cap-surface', 'gill-attachment', 'gill-spacing', 'ring-type']

# impute missing values iteratively using knn for categorical columns with missing values
imputed_train_df = std_train_df.copy()
imputed_test_df = std_test_df.copy()

for col in categorical_cols_with_nans:
    imputed_train_df = pd.DataFrame(knn_impute_categorical(imputed_train_df, col))
    imputed_test_df = pd.DataFrame(knn_impute_categorical(imputed_test_df, col))

print("missing values in train data:")
print(imputed_train_df.isnull().sum())
print()
print("missing values in test data:")
print(imputed_test_df.isnull().sum())

Here, we are verifying if the imputer worked as expected.

In [46]:
imputed_train_df

,class,cap-diameter,cap-shape,cap-surface,cap-color,does-bruise-or-bleed,gill-attachment,gill-spacing,gill-color,stem-height,stem-width,stem-color,has-ring,ring-type,habitat,season
42308,e,-0.813292,x,y,w,f,e,c,p,-0.906761,-0.138059,w,t,e,g,u
39798,p,-0.397978,c,i,y,f,x,c,r,-0.043783,-0.486727,w,f,f,d,u
40487,p,0.185757,x,t,n,f,s,c,n,-0.141984,-0.379445,n,f,f,d,w
27727,p,0.036474,x,d,n,t,d,c,w,0.250820,-0.243355,e,f,f,d,a
25153,e,1.852752,x,t,k,f,a,d,y,0.063345,1.020196,w,f,f,d,a
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54343,p,-0.229556,s,d,y,f,d,c,y,-1.222195,-0.618844,o,f,f,h,u
38158,p,0.183843,x,e,n,f,a,c,n,1.598851,0.313919,n,f,f,h,a
860,p,1.064231,f,h,n,f,e,c,w,1.253660,0.114254,w,t,g,d,u
15795,p,0.011593,x,s,n,t,s,d,r,-0.043783,0.412261,w,f,f,d,u
56422,p,0.076665,o,t,r,f,f,c,y,-1.478112,0.276171,n,f,f,d,a

In [44]:
print(imputed_train_df)
print(imputed_test_df)

      class  cap-diameter cap-shape cap-surface cap-color  \
42308     e     -0.813292         x           y         w
39798     p     -0.397978         c           i         y
40487     p      0.185757         x           t         n
27727     p      0.036474         x           d         n
25153     e      1.852752         x           t         k
...     ...           ...       ...         ...       ...
54343     p     -0.229556         s           d         y
38158     p      0.183843         x           e         n
860       p      1.064231         f           h         n
15795     p      0.011593         x           s         n
56422     p      0.076665         o           t         r

      does-bruise-or-bleed gill-attachment gill-spacing gill-color  \
42308                    f               e            c          p
39798                    f               x            c          r
40487                    f               s            c          n
27727                    t               d            c          w
25153                    f               a            d          y
...                    ...             ...          ...        ...
54343                    f               d            c          y
38158                    f               a            c          n
860                      f               e            c          w
15795                    t               s            d          r
56422                    f               f            c          y

       stem-height  stem-width stem-color has-ring ring-type habitat season
42308    -0.906761   -0.138059          w        t         e       g      u
39798    -0.043783   -0.486727          w        f         f       d      u
40487    -0.141984   -0.379445          n        f         f       d      w
27727     0.250820   -0.243355          e        f         f       d      a
25153     0.063345    1.020196          w        f         f       d      a
...            ...         ...        ...      ...       ...     ...    ...
54343    -1.222195   -0.618844          o        f         f       h      u
38158     1.598851    0.313919          n        f         f       h      a
860       1.253660    0.114254          w        t         g       d      u
15795    -0.043783    0.412261          w        f         f       d      u
56422    -1.478112    0.276171          n        f         f       d      a

[48855 rows x 16 columns]
      class  cap-diameter cap-shape cap-surface cap-color  \
11541     e     -1.033389         c           g         n
35700     p     -0.441998         x           h         o
55781     e      0.480496         o           y         n
29303     p     -0.681234         f           w         n
46601     e     -0.575970         x           h         n
...     ...           ...       ...         ...       ...
28533     p      0.947484         x           t         k
13683     p     -0.993197         x           g         n
14595     e     -0.673578         f           t         o
50231     p      0.809684         x           e         y
17552     e      0.352265         x           d         w

      does-bruise-or-bleed gill-attachment gill-spacing gill-color  \
11541                    f               a            d          g
35700                    f               a            c          n
55781                    f               e            c          w
29303                    t               d            c          y
46601                    f               x            c          n
...                    ...             ...          ...        ...
28533                    t               d            c          b
13683                    f               d            d          n
14595                    f               a            d          y
50231                    t               p            c          e
17552                    f               s            c          w

       stem-height  stem-width stem-color has-ring ring-type habitat season
11541    -0.644892   -1.079762          g        f         f       l      a
35700    -0.713335   -0.590037          o        t         z       d      w
55781    -0.618110    0.857285          n        f         f       d      a
29303    -1.025793   -0.649638          n        f         f       d      u
46601    -0.216379   -0.559243          w        f         f       d      a
...            ...         ...        ...      ...       ...     ...    ...
28533    -0.564546    1.423499          g        f         f       d      u
13683    -1.373960   -0.977446          n        f         f       h      a
14595    -0.436587   -0.786721          n        f         f       d      w
50231     0.691236    1.113572          u        f         f       d      a
17552     0.149643    2.072162          w        f         f       d      s

[12214 rows x 16 columns]

In [43]:
imputed_train_df.isnull().sum()

class                   0
cap-diameter            0
cap-shape               0
cap-surface             0
cap-color               0
does-bruise-or-bleed    0
gill-attachment         0
gill-spacing            0
gill-color              0
stem-height             0
stem-width              0
stem-color              0
has-ring                0
ring-type               0
habitat                 0
season                  0
dtype: int64

In [27]:
imputed_test_df.isnull().sum()

class                   0
cap-diameter            0
cap-shape               0
cap-surface             0
cap-color               0
does-bruise-or-bleed    0
gill-attachment         0
gill-spacing            0
gill-color              0
stem-height             0
stem-width              0
stem-color              0
has-ring                0
ring-type               0
habitat                 0
season                  0
dtype: int64

Encode categorical data

In [48]:
# check data types after imputation
imputed_train_df.dtypes

class                    object
cap-diameter            float64
cap-shape                object
cap-surface              object
cap-color                object
does-bruise-or-bleed     object
gill-attachment          object
gill-spacing             object
gill-color               object
stem-height             float64
stem-width              float64
stem-color               object
has-ring                 object
ring-type                object
habitat                  object
season                   object
dtype: object

In [54]:
# encode features
from sklearn.preprocessing import OneHotEncoder

# do not encode class
imputed_train_df_no_class = imputed_train_df.drop(columns=['class'])
imputed_test_df_no_class = imputed_test_df.drop(columns=['class'])

# get categorical columns
cat_columns = imputed_train_df_no_class.select_dtypes(include=['object']).columns.tolist()

encoder = OneHotEncoder(categories = 'auto', sparse_output=False, handle_unknown='ignore')

# encode train data
encoded_train = imputed_train_df_no_class[cat_columns]
encoded_train = encoder.fit_transform(encoded_train)
# encode test data
encoded_test = imputed_test_df_no_class[cat_columns]
encoded_test = encoder.transform(encoded_test)

# get feature names 
feature_names = encoder.get_feature_names_out(cat_columns)

# encoded dataframes
encoded_train__featuresdf = pd.DataFrame(
    encoded_train,
    columns=feature_names
)

encoded_test__features_df = pd.DataFrame(
    encoded_test,
    columns=feature_names
)
encoded_test__features_df

,cap-shape_b,cap-shape_c,cap-shape_f,cap-shape_o,cap-shape_p,cap-shape_s,cap-shape_x,cap-surface_d,cap-surface_e,cap-surface_g,cap-surface_h,cap-surface_i,cap-surface_k,cap-surface_l,cap-surface_s,cap-surface_t,cap-surface_w,cap-surface_y,cap-color_b,cap-color_e,cap-color_g,cap-color_k,cap-color_l,cap-color_n,cap-color_o,cap-color_p,cap-color_r,cap-color_u,cap-color_w,cap-color_y,does-bruise-or-bleed_f,does-bruise-or-bleed_t,gill-attachment_a,gill-attachment_d,gill-attachment_e,gill-attachment_f,gill-attachment_p,gill-attachment_s,gill-attachment_x,gill-spacing_c,gill-spacing_d,gill-spacing_f,gill-color_b,gill-color_e,gill-color_f,gill-color_g,gill-color_k,gill-color_n,gill-color_o,gill-color_p,gill-color_r,gill-color_u,gill-color_w,gill-color_y,stem-color_b,stem-color_e,stem-color_f,stem-color_g,stem-color_k,stem-color_l,stem-color_n,stem-color_o,stem-color_p,stem-color_r,stem-color_u,stem-color_w,stem-color_y,has-ring_f,has-ring_t,ring-type_e,ring-type_f,ring-type_g,ring-type_l,ring-type_m,ring-type_p,ring-type_r,ring-type_z,habitat_d,habitat_g,habitat_h,habitat_l,habitat_m,habitat_p,habitat_u,habitat_w,season_a,season_s,season_u,season_w
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12209,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
12210,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
12211,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
12212,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
12213,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [55]:
# encode class column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

# encode class in train set
train_class = imputed_train_df['class']
train_class_encoded = le.fit_transform(train_class)
# convert to series
train_class_encoded = pd.Series(train_class_encoded, name='class')

# encode class in test set
test_class = imputed_test_df['class']
test_class_encoded = le.transform(test_class)
# convert to series
test_class_encoded = pd.Series(test_class_encoded, name='class')
train_class_encoded

0        0
1        1
2        1
3        1
4        0
        ..
48850    1
48851    1
48852    1
48853    1
48854    1
Name: class, Length: 48855, dtype: int64

In [56]:
# concatenate encoded features with class column (train set)
final_train_df = pd.concat(
    [encoded_train__featuresdf, pd.DataFrame(train_class_encoded, columns=['class'])],
    axis=1
)


# concatenate encoded features with class column (test)
final_test_df = pd.concat(
    [encoded_test__features_df, pd.DataFrame(test_class_encoded, columns=['class'])],
    axis=1
)

final_train_df

,cap-shape_b,cap-shape_c,cap-shape_f,cap-shape_o,cap-shape_p,cap-shape_s,cap-shape_x,cap-surface_d,cap-surface_e,cap-surface_g,cap-surface_h,cap-surface_i,cap-surface_k,cap-surface_l,cap-surface_s,cap-surface_t,cap-surface_w,cap-surface_y,cap-color_b,cap-color_e,cap-color_g,cap-color_k,cap-color_l,cap-color_n,cap-color_o,cap-color_p,cap-color_r,cap-color_u,cap-color_w,cap-color_y,does-bruise-or-bleed_f,does-bruise-or-bleed_t,gill-attachment_a,gill-attachment_d,gill-attachment_e,gill-attachment_f,gill-attachment_p,gill-attachment_s,gill-attachment_x,gill-spacing_c,gill-spacing_d,gill-spacing_f,gill-color_b,gill-color_e,gill-color_f,gill-color_g,gill-color_k,gill-color_n,gill-color_o,gill-color_p,gill-color_r,gill-color_u,gill-color_w,gill-color_y,stem-color_b,stem-color_e,stem-color_f,stem-color_g,stem-color_k,stem-color_l,stem-color_n,stem-color_o,stem-color_p,stem-color_r,stem-color_u,stem-color_w,stem-color_y,has-ring_f,has-ring_t,ring-type_e,ring-type_f,ring-type_g,ring-type_l,ring-type_m,ring-type_p,ring-type_r,ring-type_z,habitat_d,habitat_g,habitat_h,habitat_l,habitat_m,habitat_p,habitat_u,habitat_w,season_a,season_s,season_u,season_w,class
0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1
2,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1
3,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1
4,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48850,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1
48851,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1
48852,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1
48853,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1
48854,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1

In [51]:
# export clean data to CSV
df.to_csv('../Data/clean_data.csv', index=False)

## preprocessing funciton to preprocess train and test data

In [ ]:
# import preprocessing functions from preprocessing.py
# First, reload the module to get the latest changes
import importlib
import preprocessing
importlib.reload(preprocessing)

from preprocessing import preprocess_mushroom_data
processed_train_df, processed_test_df, encoders = preprocess_mushroom_data(train_df, test_df, fit_encoders=True)

NameError: name 'numeric_cols' is not defined

In [70]:
processed_train_df[processed_train_df.isna().sum(axis=1)>=1]

Empty DataFrame
Columns: [cap-diameter, stem-height, stem-width, cap-shape_b, cap-shape_c, cap-shape_f, cap-shape_o, cap-shape_p, cap-shape_s, cap-shape_x, cap-surface_d, cap-surface_e, cap-surface_g, cap-surface_h, cap-surface_i, cap-surface_k, cap-surface_l, cap-surface_s, cap-surface_t, cap-surface_w, cap-surface_y, cap-color_b, cap-color_e, cap-color_g, cap-color_k, cap-color_l, cap-color_n, cap-color_o, cap-color_p, cap-color_r, cap-color_u, cap-color_w, cap-color_y, does-bruise-or-bleed_f, does-bruise-or-bleed_t, gill-attachment_a, gill-attachment_d, gill-attachment_e, gill-attachment_f, gill-attachment_p, gill-attachment_s, gill-attachment_x, gill-spacing_c, gill-spacing_d, gill-spacing_f, gill-color_b, gill-color_e, gill-color_f, gill-color_g, gill-color_k, gill-color_n, gill-color_o, gill-color_p, gill-color_r, gill-color_u, gill-color_w, gill-color_y, stem-color_b, stem-color_e, stem-color_f, stem-color_g, stem-color_k, stem-color_l, stem-color_n, stem-color_o, stem-color_p, stem-color_r, stem-color_u, stem-color_w, stem-color_y, has-ring_f, has-ring_t, ring-type_e, ring-type_f, ring-type_g, ring-type_l, ring-type_m, ring-type_p, ring-type_r, ring-type_z, habitat_d, habitat_g, habitat_h, habitat_l, habitat_m, habitat_p, habitat_u, habitat_w, season_a, season_s, season_u, season_w, class]
Index: []

In [ ]:
# Example: Cross-validation usage
from sklearn.model_selection import KFold
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

def demonstrate_cv_preprocessing():
    """
    Demonstrate how to use the preprocessing function with cross-validation
    """
    print("=== Cross-Validation Example ===")
    
    # Simulate cross-validation
    kf = KFold(n_splits=3, shuffle=True, random_state=42)
    cv_scores = []
    
    for fold, (train_idx, val_idx) in enumerate(kf.split(df), 1):
        print(f"\nProcessing Fold {fold}...")
        
        # Split data
        fold_train = df.iloc[train_idx].copy()
        fold_val = df.iloc[val_idx].copy()
        
        # Preprocess training fold (fit encoders)
        processed_train, train_encoders = preprocess_mushroom_data(
            fold_train, test_df=None, fit_encoders=True
        )
        
        # Preprocess validation fold (use fitted encoders)
        processed_val, _ = preprocess_mushroom_data(
            fold_val, test_df=None, fit_encoders=False, encoders=train_encoders
        )
        
        # Prepare data for modeling
        X_train = processed_train.drop(columns=['class'])
        y_train = processed_train['class']
        X_val = processed_val.drop(columns=['class'])
        y_val = processed_val['class']
        
        # Train a simple model
        model = KNeighborsClassifier(n_neighbors=5)
        model.fit(X_train, y_train)
        
        # Evaluate
        y_pred = model.predict(X_val)
        score = accuracy_score(y_val, y_pred)
        cv_scores.append(score)
        
        print(f"Fold {fold} accuracy: {score:.4f}")
        print(f"Training features: {X_train.shape[1]}")
        print(f"No missing values in train: {X_train.isnull().sum().sum() == 0}")
        print(f"No missing values in val: {X_val.isnull().sum().sum() == 0}")
    
    print(f"\n=== Cross-Validation Results ===")
    print(f"Mean CV Accuracy: {np.mean(cv_scores):.4f} (+/- {np.std(cv_scores) * 2:.4f})")
    
    return cv_scores

import numpy as np

# Run the demonstration
cv_results = demonstrate_cv_preprocessing()